Task: example-data
date: Jun9
multianimalproject: true

project_path:

individuals:
  - individual1
  - individual2
  - individual3
uniquebodyparts: []
multianimalbodyparts:
  - bodypart1
  - bodypart2
  - bodypart3
skeleton:
  - - bodypart1
    - bodypart2
  - - bodypart1
    - bodypart3
  - - bodypart2
    - bodypart3
bodyparts: MULTI!

TrainingFraction:
  - 0.95
iteration: 0
snapshotindex: -1
cropping: false
